STATUS_EVENTO_PLANEJADO = "planejado"
STATUS_EVENTO_CONFIRMADO = "confirmado"
STATUS_EVENTO_EM_ANDAMENTO = "em_andamento"
STATUS_EVENTO_CONCLUIDO = "concluido"
STATUS_EVENTO_CANCELADO = "cancelado"

STATUS_EVENTOS_ABERTOS = (
    STATUS_EVENTO_PLANEJADO,
    STATUS_EVENTO_CONFIRMADO,
    STATUS_EVENTO_EM_ANDAMENTO,
)
