STATUS_PARCELA_ABERTA = "aberta"
STATUS_PARCELA_PARCIAL = "parcial"
STATUS_PARCELA_PAGA = "paga"
STATUS_PARCELA_VENCIDA = "vencida"
STATUS_PARCELA_PRORROGADA = "prorrogada"
STATUS_PARCELA_RENEGOCIADA = "renegociada"
STATUS_PARCELA_CANCELADA = "cancelada"

STATUS_DIVIDA_ATIVA = "ativa"
STATUS_DIVIDA_QUITADA = "quitada"
STATUS_DIVIDA_RENEGOCIADA = "renegociada"
STATUS_DIVIDA_CANCELADA = "cancelada"

STATUS_PARCELAS = (
    STATUS_PARCELA_ABERTA,
    STATUS_PARCELA_PARCIAL,
    STATUS_PARCELA_PAGA,
    STATUS_PARCELA_VENCIDA,
    STATUS_PARCELA_PRORROGADA,
    STATUS_PARCELA_RENEGOCIADA,
    STATUS_PARCELA_CANCELADA,
)
STATUS_PARCELAS_PENDENTES = (
    STATUS_PARCELA_ABERTA,
    STATUS_PARCELA_PARCIAL,
    STATUS_PARCELA_VENCIDA,
    STATUS_PARCELA_PRORROGADA,
    STATUS_PARCELA_RENEGOCIADA,
)
STATUS_PARCELAS_EM_ABERTO = STATUS_PARCELAS_PENDENTES
STATUS_PARCELAS_FINAIS = (
    STATUS_PARCELA_PAGA,
    STATUS_PARCELA_CANCELADA,
)
STATUS_DIVIDAS = (
    STATUS_DIVIDA_ATIVA,
    STATUS_DIVIDA_QUITADA,
    STATUS_DIVIDA_RENEGOCIADA,
    STATUS_DIVIDA_CANCELADA,
)
