# Generated by Django 6.0.6 on 2026-07-07 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoTenantSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupado', 'Ocupado'), ('expirado', 'Expirado'), ('bloqueado', 'Bloqueado')], default='livre', max_length=20)),
                ('assigned_name', models.CharField(blank=True, max_length=150)),
                ('assigned_email', models.EmailField(blank=True, max_length=254)),
                ('assigned_phone', models.CharField(blank=True, max_length=30)),
                ('lease_started_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('max_storage_mb', models.PositiveIntegerField(default=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_slot', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['slot_code'],
                'indexes': [models.Index(fields=['status', 'lease_expires_at'], name='demo_slot_status_exp_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('slot_code__in', ('demo1', 'demo2', 'demo3', 'demo4', 'demo5', 'demo6', 'demo7', 'demo8', 'demo9', 'demo10'))), name='demo_slot_code_allowed'), models.CheckConstraint(condition=models.Q(('status__in', ('livre', 'ocupado', 'expirado', 'bloqueado'))), name='demo_slot_status_allowed'), models.CheckConstraint(condition=models.Q(('max_storage_mb__gte', 1), ('max_storage_mb__lte', 50)), name='demo_slot_storage_range'), models.CheckConstraint(condition=models.Q(('lease_started_at__isnull', True), ('lease_expires_at__isnull', True), ('lease_expires_at__gt', models.F('lease_started_at')), _connector='OR'), name='demo_slot_lease_order')],
            },
        ),
    ]
