# Generated by Django 6.0.3 on 2026-03-14 05:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Padrão', max_length=100)),
                ('valor_alimentacao', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10)),
                ('valor_transporte', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=10)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Use 0.30 para 30%', max_digits=5)),
                ('aliquota_imposto', models.DecimalField(decimal_places=2, default=Decimal('0.06'), help_text='Use 0.06 para 6%', max_digits=5)),
                ('ativa', models.BooleanField(default=True)),
                ('data_inicio_vigencia', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configurações Financeiras',
                'ordering': ['-data_inicio_vigencia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo', models.SlugField(unique=True)),
                ('diaria_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_base_diaria', models.PositiveIntegerField(default=8)),
                ('percentual_hora_extra', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('usa_regra_especial', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
            },
        ),
    ]
