# Generated by Django 6.0.3 on 2026-03-14 19:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_cliente_evento_despesaoperacional_orcamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('equipamento', 'Equipamento'), ('veiculo', 'Veículo'), ('moveis', 'Móveis'), ('informatica', 'Informática'), ('software', 'Software'), ('reforma', 'Reforma'), ('imovel', 'Imóvel'), ('outros', 'Outros')], max_length=30)),
                ('tipo_fluxo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='saida', max_length=10)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_prevista', models.DateField()),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('parcial', 'Parcial'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['-data_prevista', '-id'],
            },
        ),
    ]
