# Generated by Django 6.0.3 on 2026-03-14 20:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_investimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanciamentoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('emprestimo', 'Empréstimo'), ('financiamento', 'Financiamento'), ('aporte_socio', 'Aporte de Sócio'), ('retirada_socio', 'Retirada de Sócio'), ('amortizacao', 'Amortização'), ('juros', 'Juros'), ('encargo_bancario', 'Encargo Bancário'), ('outros', 'Outros')], max_length=30)),
                ('tipo_fluxo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_prevista', models.DateField()),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('parcial', 'Parcial'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimentação de Financiamento',
                'verbose_name_plural': 'Movimentações de Financiamento',
                'ordering': ['-data_prevista', '-id'],
            },
        ),
    ]
