# Generated by Django 6.0.3 on 2026-03-14 23:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_financiamentomovimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCustoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_diarias', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_alimentacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_transporte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_servicos', to='caixa.evento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos_evento', to='caixa.servico')),
            ],
            options={
                'verbose_name': 'Custo por Serviço do Evento',
                'verbose_name_plural': 'Custos por Serviço dos Eventos',
                'ordering': ['evento', 'servico__nome'],
                'unique_together': {('evento', 'servico')},
            },
        ),
    ]
