# Generated by Django 6.0.3 on 2026-03-15 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_eventocustoservico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesaoperacional',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesaoperacional',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventocustoservico',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_servico_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventocustoservico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_servico_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financiamentomovimentacao',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financiamentos_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financiamentomovimentacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financiamentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investimento',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investimentos_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investimento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investimentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receitaoperacional',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receitaoperacional',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_criadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
