# Generated by Django 6.0.3 on 2026-03-15 19:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0007_historicaldespesaoperacional_historicalevento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DividaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('credor', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('emprestimo', 'Empréstimo'), ('financiamento', 'Financiamento'), ('fornecedor', 'Fornecedor'), ('tributaria', 'Tributária'), ('trabalhista', 'Trabalhista'), ('cartao', 'Cartão'), ('outros', 'Outros')], max_length=30)),
                ('data_contratacao', models.DateField()),
                ('valor_contratado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_juros_mensal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Ex.: 0.0200 para 2% ao mês', max_digits=7)),
                ('quantidade_parcelas', models.PositiveIntegerField(default=1)),
                ('dia_vencimento', models.PositiveIntegerField(default=10)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('quitada', 'Quitada'), ('renegociada', 'Renegociada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividas_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dívida Financeira',
                'verbose_name_plural': 'Dívidas Financeiras',
                'ordering': ['-data_contratacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaDivida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField()),
                ('data_vencimento_original', models.DateField()),
                ('data_vencimento_atual', models.DateField()),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Parcial'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('prorrogada', 'Prorrogada'), ('renegociada', 'Renegociada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_divida_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_divida_criadas', to=settings.AUTH_USER_MODEL)),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='caixa.dividafinanceira')),
                ('parcela_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_derivadas', to='caixa.parceladivida')),
            ],
            options={
                'verbose_name': 'Parcela da Dívida',
                'verbose_name_plural': 'Parcelas das Dívidas',
                'ordering': ['data_vencimento_atual', 'numero_parcela', 'id'],
                'unique_together': {('divida', 'numero_parcela')},
            },
        ),
        migrations.CreateModel(
            name='PagamentoParcelaDivida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_divida_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_divida_criados', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='caixa.parceladivida')),
            ],
            options={
                'verbose_name': 'Pagamento de Parcela',
                'verbose_name_plural': 'Pagamentos de Parcelas',
                'ordering': ['data_pagamento', 'id'],
            },
        ),
    ]
