# Generated by Django 6.0.3 on 2026-03-16 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0009_custofixo_historicalcustofixo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custofixo',
            options={'ordering': ['data_vencimento', 'descricao', 'id'], 'verbose_name': 'Custo Fixo', 'verbose_name_plural': 'Custos Fixos'},
        ),
        migrations.AddField(
            model_name='custofixo',
            name='custo_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_filhos', to='caixa.custofixo'),
        ),
        migrations.AddField(
            model_name='custofixo',
            name='gerado_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custofixo',
            name='quantidade_meses',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='custofixo',
            name='recorrente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='custo_pai',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.custofixo'),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='gerado_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='quantidade_meses',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='recorrente',
            field=models.BooleanField(default=True),
        ),
    ]
