# Generated by Django 6.0.3 on 2026-03-24 22:24

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0010_alter_custofixo_options_custofixo_custo_pai_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCustoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('insumo', 'Insumo'), ('material', 'Material'), ('uniforme', 'Uniforme'), ('logistica', 'Logística'), ('comissao', 'Comissão'), ('outros', 'Outros')], default='insumo', max_length=30)),
                ('descricao', models.CharField(max_length=150)),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_extras_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_extras_criados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_extras', to='caixa.evento')),
            ],
            options={
                'verbose_name': 'Custo Extra do Evento',
                'verbose_name_plural': 'Custos Extras do Evento',
                'ordering': ['data_vencimento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEventoCustoExtra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('insumo', 'Insumo'), ('material', 'Material'), ('uniforme', 'Uniforme'), ('logistica', 'Logística'), ('comissao', 'Comissão'), ('outros', 'Outros')], default='insumo', max_length=30)),
                ('descricao', models.CharField(max_length=150)),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.evento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Custo Extra do Evento',
                'verbose_name_plural': 'historical Custos Extras do Evento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
