# Generated by Django 6.0.3 on 2026-03-24 23:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0011_eventocustoextra_historicaleventocustoextra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPagamentoEventoCustoExtra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('custo_extra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.eventocustoextra')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pagamento de Custo Extra',
                'verbose_name_plural': 'historical Pagamentos de Custos Extras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPagamentoEventoCustoServico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diarias', 'Diárias'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('custo_servico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.eventocustoservico')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pagamento de Custo de Serviço',
                'verbose_name_plural': 'historical Pagamentos de Custos de Serviço',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PagamentoEventoCustoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_evento_custo_extra_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_evento_custo_extra_criados', to=settings.AUTH_USER_MODEL)),
                ('custo_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='caixa.eventocustoextra')),
            ],
            options={
                'verbose_name': 'Pagamento de Custo Extra',
                'verbose_name_plural': 'Pagamentos de Custos Extras',
                'ordering': ['data_pagamento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoEventoCustoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diarias', 'Diárias'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_evento_custo_servico_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_evento_custo_servico_criados', to=settings.AUTH_USER_MODEL)),
                ('custo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='caixa.eventocustoservico')),
            ],
            options={
                'verbose_name': 'Pagamento de Custo de Serviço',
                'verbose_name_plural': 'Pagamentos de Custos de Serviço',
                'ordering': ['data_pagamento', 'id'],
            },
        ),
    ]
