# Generated by Django 6.0.3 on 2026-05-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0012_historicalpagamentoeventocustoextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocustoextra',
            name='quitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventocustoservico',
            name='alimentacao_quitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventocustoservico',
            name='diarias_quitadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventocustoservico',
            name='transporte_quitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleventocustoextra',
            name='quitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleventocustoservico',
            name='alimentacao_quitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleventocustoservico',
            name='diarias_quitadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleventocustoservico',
            name='transporte_quitado',
            field=models.BooleanField(default=False),
        ),
    ]
