# Generated by Django 6.0.3 on 2026-05-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0013_eventocustoextra_quitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custofixo',
            name='baixado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AddField(
            model_name='custofixo',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='despesaoperacional',
            name='baixado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AddField(
            model_name='despesaoperacional',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='eventocustoextra',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='eventocustoservico',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='baixado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='historicaldespesaoperacional',
            name='baixado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AddField(
            model_name='historicaldespesaoperacional',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='historicaleventocustoextra',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='historicaleventocustoservico',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='historicalinvestimento',
            name='baixado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AddField(
            model_name='historicalinvestimento',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='historicalreceitaoperacional',
            name='baixado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AddField(
            model_name='historicalreceitaoperacional',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='baixado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='parceladivida',
            name='baixado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AddField(
            model_name='parceladivida',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AddField(
            model_name='receitaoperacional',
            name='baixado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AddField(
            model_name='receitaoperacional',
            name='motivo_baixa',
            field=models.TextField(blank=True, verbose_name='Motivo da baixa'),
        ),
        migrations.AlterField(
            model_name='eventocustoextra',
            name='quitado',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AlterField(
            model_name='eventocustoservico',
            name='alimentacao_quitada',
            field=models.BooleanField(default=False, verbose_name='Alimentacao baixada'),
        ),
        migrations.AlterField(
            model_name='eventocustoservico',
            name='diarias_quitadas',
            field=models.BooleanField(default=False, verbose_name='Diarias baixadas'),
        ),
        migrations.AlterField(
            model_name='eventocustoservico',
            name='transporte_quitado',
            field=models.BooleanField(default=False, verbose_name='Transporte baixado'),
        ),
        migrations.AlterField(
            model_name='historicaleventocustoextra',
            name='quitado',
            field=models.BooleanField(default=False, verbose_name='Baixa manual'),
        ),
        migrations.AlterField(
            model_name='historicaleventocustoservico',
            name='alimentacao_quitada',
            field=models.BooleanField(default=False, verbose_name='Alimentacao baixada'),
        ),
        migrations.AlterField(
            model_name='historicaleventocustoservico',
            name='diarias_quitadas',
            field=models.BooleanField(default=False, verbose_name='Diarias baixadas'),
        ),
        migrations.AlterField(
            model_name='historicaleventocustoservico',
            name='transporte_quitado',
            field=models.BooleanField(default=False, verbose_name='Transporte baixado'),
        ),
    ]
