# Generated by Django 6.0.3 on 2026-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0014_custofixo_baixado_manualmente_custofixo_motivo_baixa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_razao_social',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='configuracaofinanceira',
            name='ativa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='configuracaofinanceira',
            name='data_inicio_vigencia',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='categoria',
            field=models.CharField(choices=[('aluguel', 'Aluguel'), ('energia', 'Energia'), ('agua', 'Água'), ('internet', 'Internet'), ('telefone', 'Telefone'), ('salario', 'Salário'), ('contador', 'Contador'), ('sistema', 'Sistema'), ('imposto', 'Imposto'), ('outro', 'Outro')], db_index=True, default='outro', max_length=30),
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='data_pagamento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='despesaoperacional',
            name='categoria',
            field=models.CharField(choices=[('mao_obra', 'Mão de obra'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('imposto', 'Imposto'), ('uniforme', 'Uniforme'), ('material', 'Material'), ('comissao', 'Comissão'), ('outros', 'Outros')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='despesaoperacional',
            name='data_pagamento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesaoperacional',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='despesaoperacional',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='dividafinanceira',
            name='credor',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='dividafinanceira',
            name='data_contratacao',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dividafinanceira',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('quitada', 'Quitada'), ('renegociada', 'Renegociada'), ('cancelada', 'Cancelada')], db_index=True, default='ativa', max_length=20),
        ),
        migrations.AlterField(
            model_name='dividafinanceira',
            name='tipo',
            field=models.CharField(choices=[('emprestimo', 'Empréstimo'), ('financiamento', 'Financiamento'), ('fornecedor', 'Fornecedor'), ('tributaria', 'Tributária'), ('trabalhista', 'Trabalhista'), ('cartao', 'Cartão'), ('outros', 'Outros')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='planejado', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventocustoextra',
            name='categoria',
            field=models.CharField(choices=[('insumo', 'Insumo'), ('material', 'Material'), ('uniforme', 'Uniforme'), ('logistica', 'Logística'), ('comissao', 'Comissão'), ('outros', 'Outros')], db_index=True, default='insumo', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventocustoextra',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='financiamentomovimentacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='financiamentomovimentacao',
            name='categoria',
            field=models.CharField(choices=[('emprestimo', 'Empréstimo'), ('financiamento', 'Financiamento'), ('aporte_socio', 'Aporte de Sócio'), ('retirada_socio', 'Retirada de Sócio'), ('amortizacao', 'Amortização'), ('juros', 'Juros'), ('encargo_bancario', 'Encargo Bancário'), ('outros', 'Outros')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='financiamentomovimentacao',
            name='data_prevista',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='financiamentomovimentacao',
            name='data_realizacao',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='financiamentomovimentacao',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('parcial', 'Parcial'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], db_index=True, default='planejado', max_length=20),
        ),
        migrations.AlterField(
            model_name='financiamentomovimentacao',
            name='tipo_fluxo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcustofixo',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='historicalcustofixo',
            name='categoria',
            field=models.CharField(choices=[('aluguel', 'Aluguel'), ('energia', 'Energia'), ('agua', 'Água'), ('internet', 'Internet'), ('telefone', 'Telefone'), ('salario', 'Salário'), ('contador', 'Contador'), ('sistema', 'Sistema'), ('imposto', 'Imposto'), ('outro', 'Outro')], db_index=True, default='outro', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcustofixo',
            name='data_pagamento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustofixo',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcustofixo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldespesaoperacional',
            name='categoria',
            field=models.CharField(choices=[('mao_obra', 'Mão de obra'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('imposto', 'Imposto'), ('uniforme', 'Uniforme'), ('material', 'Material'), ('comissao', 'Comissão'), ('outros', 'Outros')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicaldespesaoperacional',
            name='data_pagamento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldespesaoperacional',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldespesaoperacional',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='data_fim',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='data_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='planejado', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaleventocustoextra',
            name='categoria',
            field=models.CharField(choices=[('insumo', 'Insumo'), ('material', 'Material'), ('uniforme', 'Uniforme'), ('logistica', 'Logística'), ('comissao', 'Comissão'), ('outros', 'Outros')], db_index=True, default='insumo', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicaleventocustoextra',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinvestimento',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='historicalinvestimento',
            name='categoria',
            field=models.CharField(choices=[('equipamento', 'Equipamento'), ('veiculo', 'Veículo'), ('moveis', 'Móveis'), ('informatica', 'Informática'), ('software', 'Software'), ('reforma', 'Reforma'), ('imovel', 'Imóvel'), ('outros', 'Outros')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalinvestimento',
            name='data_prevista',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinvestimento',
            name='data_realizacao',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinvestimento',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('parcial', 'Parcial'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], db_index=True, default='planejado', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalinvestimento',
            name='tipo_fluxo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], db_index=True, default='saida', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpagamentoeventocustoextra',
            name='data_pagamento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpagamentoeventocustoservico',
            name='data_pagamento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpagamentoeventocustoservico',
            name='tipo',
            field=models.CharField(choices=[('diarias', 'Diárias'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalreceitaoperacional',
            name='data_recebimento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreceitaoperacional',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalreceitaoperacional',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('recebido', 'Recebido'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='categoria',
            field=models.CharField(choices=[('equipamento', 'Equipamento'), ('veiculo', 'Veículo'), ('moveis', 'Móveis'), ('informatica', 'Informática'), ('software', 'Software'), ('reforma', 'Reforma'), ('imovel', 'Imóvel'), ('outros', 'Outros')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='data_prevista',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='data_realizacao',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('parcial', 'Parcial'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], db_index=True, default='planejado', max_length=20),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='tipo_fluxo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], db_index=True, default='saida', max_length=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data_evento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamentoeventocustoextra',
            name='data_pagamento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pagamentoeventocustoservico',
            name='data_pagamento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pagamentoeventocustoservico',
            name='tipo',
            field=models.CharField(choices=[('diarias', 'Diárias'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamentoparceladivida',
            name='data_pagamento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parceladivida',
            name='data_vencimento_atual',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parceladivida',
            name='data_vencimento_original',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parceladivida',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Parcial'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('prorrogada', 'Prorrogada'), ('renegociada', 'Renegociada'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='receitaoperacional',
            name='data_recebimento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='receitaoperacional',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='receitaoperacional',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('recebido', 'Recebido'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
    ]
