# Generated by Django 6.0.5 on 2026-05-20 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0015_alter_cliente_ativo_alter_cliente_nome_razao_social_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ativo', 'nome_razao_social'], name='caixa_clien_ativo_28fc63_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tipo_pessoa', 'ativo'], name='caixa_clien_tipo_pe_065b10_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracaofinanceira',
            index=models.Index(fields=['ativa', 'data_inicio_vigencia'], name='caixa_confi_ativa_a7fa7f_idx'),
        ),
        migrations.AddIndex(
            model_name='custofixo',
            index=models.Index(fields=['status', 'data_vencimento'], name='caixa_custo_status_f35b40_idx'),
        ),
        migrations.AddIndex(
            model_name='custofixo',
            index=models.Index(fields=['categoria', 'data_vencimento'], name='caixa_custo_categor_e92ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='custofixo',
            index=models.Index(fields=['ativo', 'data_vencimento'], name='caixa_custo_ativo_ede0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='custofixo',
            index=models.Index(fields=['custo_pai', 'data_vencimento'], name='caixa_custo_custo_p_471eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='despesaoperacional',
            index=models.Index(fields=['status', 'data_vencimento'], name='caixa_despe_status_3b4603_idx'),
        ),
        migrations.AddIndex(
            model_name='despesaoperacional',
            index=models.Index(fields=['categoria', 'data_vencimento'], name='caixa_despe_categor_0a06b1_idx'),
        ),
        migrations.AddIndex(
            model_name='despesaoperacional',
            index=models.Index(fields=['evento', 'status'], name='caixa_despe_evento__85ff10_idx'),
        ),
        migrations.AddIndex(
            model_name='dividafinanceira',
            index=models.Index(fields=['status', 'data_contratacao'], name='caixa_divid_status_6da9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='dividafinanceira',
            index=models.Index(fields=['tipo', 'status'], name='caixa_divid_tipo_974f99_idx'),
        ),
        migrations.AddIndex(
            model_name='dividafinanceira',
            index=models.Index(fields=['credor', 'status'], name='caixa_divid_credor_6c4230_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['status', 'data_inicio'], name='caixa_event_status_cac99c_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['cliente', 'data_inicio'], name='caixa_event_cliente_2d69f5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventocustoextra',
            index=models.Index(fields=['evento', 'data_vencimento'], name='caixa_event_evento__d4e10a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventocustoextra',
            index=models.Index(fields=['categoria', 'data_vencimento'], name='caixa_event_categor_6e62c3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventocustoservico',
            index=models.Index(fields=['servico', 'evento'], name='caixa_event_servico_4f6e82_idx'),
        ),
        migrations.AddIndex(
            model_name='financiamentomovimentacao',
            index=models.Index(fields=['status', 'data_prevista'], name='caixa_finan_status_eba3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='financiamentomovimentacao',
            index=models.Index(fields=['tipo_fluxo', 'data_prevista'], name='caixa_finan_tipo_fl_4310a1_idx'),
        ),
        migrations.AddIndex(
            model_name='financiamentomovimentacao',
            index=models.Index(fields=['ativo', 'data_prevista'], name='caixa_finan_ativo_31bd61_idx'),
        ),
        migrations.AddIndex(
            model_name='financiamentomovimentacao',
            index=models.Index(fields=['categoria', 'data_prevista'], name='caixa_finan_categor_b38b23_idx'),
        ),
        migrations.AddIndex(
            model_name='investimento',
            index=models.Index(fields=['status', 'data_prevista'], name='caixa_inves_status_e524c8_idx'),
        ),
        migrations.AddIndex(
            model_name='investimento',
            index=models.Index(fields=['tipo_fluxo', 'data_prevista'], name='caixa_inves_tipo_fl_4e3c53_idx'),
        ),
        migrations.AddIndex(
            model_name='investimento',
            index=models.Index(fields=['ativo', 'data_prevista'], name='caixa_inves_ativo_bff265_idx'),
        ),
        migrations.AddIndex(
            model_name='investimento',
            index=models.Index(fields=['categoria', 'data_prevista'], name='caixa_inves_categor_a14e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['status', 'data_evento'], name='caixa_orcam_status_8bf3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['cliente', 'status'], name='caixa_orcam_cliente_510328_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentoitem',
            index=models.Index(fields=['orcamento', 'servico'], name='caixa_orcam_orcamen_40c480_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentoeventocustoextra',
            index=models.Index(fields=['custo_extra', 'data_pagamento'], name='caixa_pagam_custo_e_00c07e_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentoeventocustoservico',
            index=models.Index(fields=['custo_servico', 'data_pagamento'], name='caixa_pagam_custo_s_586b88_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentoeventocustoservico',
            index=models.Index(fields=['tipo', 'data_pagamento'], name='caixa_pagam_tipo_b9f9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentoparceladivida',
            index=models.Index(fields=['parcela', 'data_pagamento'], name='caixa_pagam_parcela_8d19c0_idx'),
        ),
        migrations.AddIndex(
            model_name='parceladivida',
            index=models.Index(fields=['status', 'data_vencimento_atual'], name='caixa_parce_status_01fb2d_idx'),
        ),
        migrations.AddIndex(
            model_name='parceladivida',
            index=models.Index(fields=['divida', 'status'], name='caixa_parce_divida__d7544d_idx'),
        ),
        migrations.AddIndex(
            model_name='receitaoperacional',
            index=models.Index(fields=['status', 'data_vencimento'], name='caixa_recei_status_1c262b_idx'),
        ),
        migrations.AddIndex(
            model_name='receitaoperacional',
            index=models.Index(fields=['cliente', 'status'], name='caixa_recei_cliente_26b53b_idx'),
        ),
        migrations.AddIndex(
            model_name='receitaoperacional',
            index=models.Index(fields=['evento', 'status'], name='caixa_recei_evento__070625_idx'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['ativo', 'nome'], name='caixa_servi_ativo_7d4323_idx'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('valor_alimentacao__gte', 0), ('valor_transporte__gte', 0), ('margem_lucro__gte', 0), ('aliquota_imposto__gte', 0)), name='ck_config_fin_valores_nn'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofinanceira',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('ativa',), name='uq_config_fin_ativa'),
        ),
        migrations.AddConstraint(
            model_name='custofixo',
            constraint=models.CheckConstraint(condition=models.Q(('valor_previsto__gte', 0), ('valor_pago__gte', 0), ('valor_pago__lte', models.F('valor_previsto'))), name='ck_custo_fixo_valores'),
        ),
        migrations.AddConstraint(
            model_name='custofixo',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_meses__gte', 1)), name='ck_custo_fixo_meses_pos'),
        ),
        migrations.AddConstraint(
            model_name='despesaoperacional',
            constraint=models.CheckConstraint(condition=models.Q(('valor_previsto__gte', 0), ('valor_pago__gte', 0)), name='ck_despesa_valores_nn'),
        ),
        migrations.AddConstraint(
            model_name='dividafinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('valor_contratado__gte', 0), ('taxa_juros_mensal__gte', 0), ('quantidade_parcelas__gte', 1), ('dia_vencimento__gte', 1), ('dia_vencimento__lte', 31)), name='ck_divida_parametros_validos'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='ck_evento_periodo_valido'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total_previsto__gte', 0), ('custo_total_previsto__gte', 0), ('valor_total_realizado__gte', 0), ('custo_total_realizado__gte', 0)), name='ck_evento_valores_nn'),
        ),
        migrations.AddConstraint(
            model_name='eventocustoextra',
            constraint=models.CheckConstraint(condition=models.Q(('valor_previsto__gte', 0), ('valor_pago__gte', 0)), name='ck_custo_extra_valores_nn'),
        ),
        migrations.AddConstraint(
            model_name='eventocustoservico',
            constraint=models.CheckConstraint(condition=models.Q(('valor_diarias__gte', 0), ('valor_alimentacao__gte', 0), ('valor_transporte__gte', 0)), name='ck_custo_servico_valores_nn'),
        ),
        migrations.AddConstraint(
            model_name='financiamentomovimentacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_previsto__gte', 0), ('valor_realizado__gte', 0)), name='ck_fcf_valores_nn'),
        ),
        migrations.AddConstraint(
            model_name='investimento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_previsto__gte', 0), ('valor_realizado__gte', 0)), name='ck_investimento_valores_nn'),
        ),
        migrations.AddConstraint(
            model_name='orcamento',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_custos__gte', 0), ('total_impostos__gte', 0), ('total_lucro__gte', 0), ('total_venda__gte', 0)), name='ck_orcamento_totais_nn'),
        ),
        migrations.AddConstraint(
            model_name='orcamentoitem',
            constraint=models.CheckConstraint(condition=models.Q(('horas_por_dia__gt', 0), ('quantidade_dias__gt', 0), ('quantidade_pessoas__gt', 0)), name='ck_orc_item_qtd_pos'),
        ),
        migrations.AddConstraint(
            model_name='orcamentoitem',
            constraint=models.CheckConstraint(condition=models.Q(('valor_diaria_usada__gte', 0), ('valor_alimentacao_usado__gte', 0), ('valor_transporte_usado__gte', 0), ('margem_lucro_usada__gte', 0), ('aliquota_imposto_usada__gte', 0), ('valor_dia_por_pessoa__gte', 0), ('custo_servico_total__gte', 0), ('gasto_alimentacao_total__gte', 0), ('gasto_transporte_total__gte', 0), ('valor_horas_extras_total__gte', 0), ('custo_total__gte', 0), ('valor_com_margem__gte', 0), ('valor_imposto__gte', 0), ('lucro__gte', 0), ('preco_venda__gte', 0)), name='ck_orc_item_valores_nn'),
        ),
        migrations.AddConstraint(
            model_name='pagamentoeventocustoextra',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pagamento__gt', 0)), name='ck_pag_custo_extra_valor_pos'),
        ),
        migrations.AddConstraint(
            model_name='pagamentoeventocustoservico',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pagamento__gt', 0)), name='ck_pag_custo_serv_valor_pos'),
        ),
        migrations.AddConstraint(
            model_name='pagamentoparceladivida',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pagamento__gt', 0)), name='ck_pag_parcela_valor_pos'),
        ),
        migrations.AddConstraint(
            model_name='parceladivida',
            constraint=models.CheckConstraint(condition=models.Q(('numero_parcela__gte', 1), ('valor_principal__gte', 0), ('valor_juros__gte', 0), ('valor_multa__gte', 0), ('valor_desconto__gte', 0), ('valor_pago__gte', 0)), name='ck_parcela_divida_valores'),
        ),
        migrations.AddConstraint(
            model_name='receitaoperacional',
            constraint=models.CheckConstraint(condition=models.Q(('valor_previsto__gte', 0), ('valor_recebido__gte', 0)), name='ck_receita_valores_nn'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.CheckConstraint(condition=models.Q(('diaria_padrao__gte', 0)), name='ck_servico_diaria_nn'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.CheckConstraint(condition=models.Q(('horas_base_diaria__gt', 0)), name='ck_servico_horas_pos'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.CheckConstraint(condition=models.Q(('percentual_hora_extra__gte', 0)), name='ck_servico_extra_nn'),
        ),
    ]
