# Generated by Django 6.0.5 on 2026-05-20 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def classificar_origem_despesas(apps, schema_editor):
    despesa_model = apps.get_model('caixa', 'DespesaOperacional')
    custo_servico_model = apps.get_model('caixa', 'EventoCustoServico')
    custo_extra_model = apps.get_model('caixa', 'EventoCustoExtra')

    custos_servico = {
        'mao_obra': ('Mão de obra prevista', 'valor_diarias', 'diarias'),
        'alimentacao': ('Alimentação prevista', 'valor_alimentacao', 'alimentacao'),
        'transporte': ('Transporte previsto', 'valor_transporte', 'transporte'),
    }

    for despesa in despesa_model.objects.all().iterator():
        if despesa.descricao.startswith('Custo extra: '):
            descricao_custo = despesa.descricao.removeprefix('Custo extra: ')
            custo_extra = (
                custo_extra_model.objects
                .filter(evento_id=despesa.evento_id, descricao=descricao_custo)
                .order_by('id')
                .first()
            )
            if custo_extra:
                despesa_model.objects.filter(pk=despesa.pk).update(
                    origem='custo_extra',
                    origem_custo_extra_id=custo_extra.pk,
                    origem_custo_servico_tipo='',
                )
                continue

        regra = custos_servico.get(despesa.categoria)
        if not regra:
            continue

        descricao_esperada, campo_valor, tipo_custo = regra
        if despesa.descricao != descricao_esperada:
            continue

        if custo_servico_model.objects.filter(
            evento_id=despesa.evento_id,
            **{f'{campo_valor}__gt': 0},
        ).exists():
            despesa_model.objects.filter(pk=despesa.pk).update(
                origem='custo_servico',
                origem_custo_servico_tipo=tipo_custo,
                origem_custo_extra_id=None,
            )


def reverter_origem_despesas(apps, schema_editor):
    despesa_model = apps.get_model('caixa', 'DespesaOperacional')
    despesa_model.objects.update(
        origem='manual',
        origem_custo_extra_id=None,
        origem_custo_servico_tipo='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0016_integridade_modelagem_financeira'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesaoperacional',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('custo_servico', 'Custo de serviço'), ('custo_extra', 'Custo extra')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='despesaoperacional',
            name='origem_custo_extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_operacionais', to='caixa.eventocustoextra'),
        ),
        migrations.AddField(
            model_name='despesaoperacional',
            name='origem_custo_servico_tipo',
            field=models.CharField(blank=True, choices=[('diarias', 'Diárias'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldespesaoperacional',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('custo_servico', 'Custo de serviço'), ('custo_extra', 'Custo extra')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldespesaoperacional',
            name='origem_custo_extra',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.eventocustoextra'),
        ),
        migrations.AddField(
            model_name='historicaldespesaoperacional',
            name='origem_custo_servico_tipo',
            field=models.CharField(blank=True, choices=[('diarias', 'Diárias'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte')], max_length=20),
        ),
        migrations.RunPython(classificar_origem_despesas, reverter_origem_despesas),
        migrations.AddIndex(
            model_name='despesaoperacional',
            index=models.Index(fields=['origem', 'evento'], name='caixa_despe_origem_1b98ff_idx'),
        ),
    ]
