# Generated by Django 6.0.5 on 2026-05-21 00:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def status_contrato_por_orcamento(status):
    if status == 'cancelado':
        return 'cancelado'

    if status in {'aprovado', 'enviado'}:
        return 'ativo'

    return 'rascunho'


def status_contrato_por_evento(status):
    if status == 'cancelado':
        return 'cancelado'

    if status == 'concluido':
        return 'concluido'

    return 'ativo'


def criar_contratos_operacionais_iniciais(apps, schema_editor):
    ContratoOperacional = apps.get_model('caixa', 'ContratoOperacional')
    Orcamento = apps.get_model('caixa', 'Orcamento')
    Evento = apps.get_model('caixa', 'Evento')

    for orcamento in Orcamento.objects.filter(
        contrato_operacional__isnull=True,
    ).iterator():
        contrato, _created = ContratoOperacional.objects.get_or_create(
            codigo=orcamento.numero,
            defaults={
                'cliente_id': orcamento.cliente_id,
                'nome': orcamento.nome_evento,
                'status': status_contrato_por_orcamento(orcamento.status),
                'data_inicio_prevista': orcamento.data_evento,
                'data_fim_prevista': orcamento.data_evento,
                'observacoes': orcamento.observacoes,
            },
        )
        if contrato.cliente_id == orcamento.cliente_id:
            orcamento.contrato_operacional_id = contrato.id
            orcamento.save(update_fields=['contrato_operacional'])

    for evento in Evento.objects.filter(
        contrato_operacional__isnull=True,
    ).iterator():
        contrato_id = None
        if evento.orcamento_id:
            contrato_id = (
                Orcamento.objects.filter(pk=evento.orcamento_id)
                .values_list('contrato_operacional_id', flat=True)
                .first()
            )

        if contrato_id:
            evento.contrato_operacional_id = contrato_id
            evento.save(update_fields=['contrato_operacional'])
            continue

        contrato, _created = ContratoOperacional.objects.get_or_create(
            codigo=evento.numero,
            defaults={
                'cliente_id': evento.cliente_id,
                'nome': evento.nome_evento,
                'status': status_contrato_por_evento(evento.status),
                'data_inicio_prevista': evento.data_inicio,
                'data_fim_prevista': evento.data_fim,
                'observacoes': evento.observacoes,
            },
        )
        if contrato.cliente_id == evento.cliente_id:
            evento.contrato_operacional_id = contrato.id
            evento.save(update_fields=['contrato_operacional'])


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0017_origem_explicita_despesa_operacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=20)),
                ('data_inicio_prevista', models.DateField(blank=True, db_index=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, db_index=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_operacionais', to='caixa.cliente')),
            ],
            options={
                'verbose_name': 'Contrato Operacional',
                'verbose_name_plural': 'Contratos Operacionais',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='contrato_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='caixa.contratooperacional'),
        ),
        migrations.AddField(
            model_name='historicalevento',
            name='contrato_operacional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.contratooperacional'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='caixa.contratooperacional'),
        ),
        migrations.CreateModel(
            name='HistoricalContratoOperacional',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30)),
                ('nome', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=20)),
                ('data_inicio_prevista', models.DateField(blank=True, db_index=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, db_index=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contrato Operacional',
                'verbose_name_plural': 'historical Contratos Operacionais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(
            criar_contratos_operacionais_iniciais,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='contratooperacional',
            index=models.Index(fields=['cliente', 'status'], name='caixa_contr_cliente_5fa07a_idx'),
        ),
        migrations.AddIndex(
            model_name='contratooperacional',
            index=models.Index(fields=['status', 'data_inicio_prevista'], name='caixa_contr_status_8cc6ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='contratooperacional',
            constraint=models.CheckConstraint(condition=models.Q(('data_inicio_prevista__isnull', True), ('data_fim_prevista__isnull', True), ('data_fim_prevista__gte', models.F('data_inicio_prevista')), _connector='OR'), name='ck_contrato_operacional_periodo'),
        ),
    ]
