# Generated by Django 6.0.5 on 2026-05-21 01:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0018_contratooperacional_evento_contrato_operacional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLancamentoFinanceiro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], db_index=True, max_length=10)),
                ('fluxo', models.CharField(choices=[('fco', 'FCO - Fluxo de Caixa Operacional'), ('fci', 'FCI - Fluxo de Investimento'), ('fcf', 'FCF - Fluxo de Financiamento')], db_index=True, max_length=10)),
                ('natureza', models.CharField(choices=[('receita_operacional', 'Receita operacional'), ('despesa_operacional', 'Despesa operacional'), ('custo_servico', 'Custo de servico'), ('custo_extra', 'Custo extra'), ('parcela_divida', 'Parcela de divida'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento')], db_index=True, max_length=40)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_lancamento', models.DateField(db_index=True)),
                ('forma', models.CharField(blank=True, max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], db_index=True, default='realizado', max_length=20)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.cliente')),
                ('contrato_operacional', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.contratooperacional')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('despesa_operacional', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.despesaoperacional')),
                ('evento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.evento')),
                ('financiamento_movimentacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.financiamentomovimentacao')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.investimento')),
                ('pagamento_custo_extra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.pagamentoeventocustoextra')),
                ('pagamento_custo_servico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.pagamentoeventocustoservico')),
                ('pagamento_parcela_divida', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.pagamentoparceladivida')),
                ('receita_operacional', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.receitaoperacional')),
            ],
            options={
                'verbose_name': 'historical Lancamento Financeiro',
                'verbose_name_plural': 'historical Lancamentos Financeiros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], db_index=True, max_length=10)),
                ('fluxo', models.CharField(choices=[('fco', 'FCO - Fluxo de Caixa Operacional'), ('fci', 'FCI - Fluxo de Investimento'), ('fcf', 'FCF - Fluxo de Financiamento')], db_index=True, max_length=10)),
                ('natureza', models.CharField(choices=[('receita_operacional', 'Receita operacional'), ('despesa_operacional', 'Despesa operacional'), ('custo_servico', 'Custo de servico'), ('custo_extra', 'Custo extra'), ('parcela_divida', 'Parcela de divida'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento')], db_index=True, max_length=40)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_lancamento', models.DateField(db_index=True)),
                ('forma', models.CharField(blank=True, max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], db_index=True, default='realizado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.cliente')),
                ('contrato_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.contratooperacional')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros_criados', to=settings.AUTH_USER_MODEL)),
                ('despesa_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.despesaoperacional')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.evento')),
                ('financiamento_movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.financiamentomovimentacao')),
                ('investimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.investimento')),
                ('pagamento_custo_extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.pagamentoeventocustoextra')),
                ('pagamento_custo_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.pagamentoeventocustoservico')),
                ('pagamento_parcela_divida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.pagamentoparceladivida')),
                ('receita_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.receitaoperacional')),
            ],
            options={
                'verbose_name': 'Lancamento Financeiro',
                'verbose_name_plural': 'Lancamentos Financeiros',
                'ordering': ['-data_lancamento', '-id'],
                'indexes': [models.Index(fields=['data_lancamento', 'tipo'], name='caixa_lanca_data_la_de27f9_idx'), models.Index(fields=['fluxo', 'data_lancamento'], name='caixa_lanca_fluxo_adab53_idx'), models.Index(fields=['natureza', 'data_lancamento'], name='caixa_lanca_naturez_7d68a2_idx'), models.Index(fields=['status', 'data_lancamento'], name='caixa_lanca_status_9bb1c1_idx'), models.Index(fields=['evento', 'data_lancamento'], name='caixa_lanca_evento__3d2d13_idx'), models.Index(fields=['contrato_operacional', 'data_lancamento'], name='caixa_lanca_contrat_ab1576_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='ck_lanc_fin_valor_pos'), models.CheckConstraint(condition=models.Q(models.Q(('receita_operacional__isnull', False), ('despesa_operacional__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('despesa_operacional__isnull', False), ('receita_operacional__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('pagamento_custo_servico__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('pagamento_custo_extra__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('pagamento_parcela_divida__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('investimento__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('financiamento_movimentacao__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True)), _connector='OR'), name='ck_lanc_fin_origem_unica')],
            },
        ),
    ]
