# Generated by Django 6.0.5 on 2026-05-21 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0020_backfill_lancamentos_financeiros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='contrato_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='caixa.contratooperacional'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='despesa_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='caixa.despesaoperacional'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='caixa.evento'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='financiamento_movimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='caixa.financiamentomovimentacao'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='investimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='caixa.investimento'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='pagamento_custo_extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='caixa.pagamentoeventocustoextra'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='pagamento_custo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='caixa.pagamentoeventocustoservico'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='pagamento_parcela_divida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='caixa.pagamentoparceladivida'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='receita_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='caixa.receitaoperacional'),
        ),
    ]
