# Generated by Django 6.0.5 on 2026-05-21 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0021_alter_lancamentofinanceiro_contrato_operacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='caixa.cliente'),
        ),
    ]
