# Generated by Django 6.0.5 on 2026-05-21 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0022_alter_lancamentofinanceiro_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('receita_operacional__isnull', False)), fields=('receita_operacional',), name='uq_lanc_fin_receita'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('despesa_operacional__isnull', False)), fields=('despesa_operacional',), name='uq_lanc_fin_despesa'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('pagamento_custo_servico__isnull', False)), fields=('pagamento_custo_servico',), name='uq_lanc_fin_pag_serv'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('pagamento_custo_extra__isnull', False)), fields=('pagamento_custo_extra',), name='uq_lanc_fin_pag_extra'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('pagamento_parcela_divida__isnull', False)), fields=('pagamento_parcela_divida',), name='uq_lanc_fin_pag_parc'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('investimento__isnull', False)), fields=('investimento',), name='uq_lanc_fin_invest'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('financiamento_movimentacao__isnull', False)), fields=('financiamento_movimentacao',), name='uq_lanc_fin_financ'),
        ),
    ]
