# Generated by Django 6.0.5 on 2026-05-21 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0023_lancamentofinanceiro_uq_lanc_fin_receita_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lancamentofinanceiro',
            name='ck_lanc_fin_origem_unica',
        ),
        migrations.AddField(
            model_name='historicallancamentofinanceiro',
            name='custo_fixo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.custofixo'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='custo_fixo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='caixa.custofixo'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('receita_operacional__isnull', False), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('despesa_operacional__isnull', False), ('receita_operacional__isnull', True), ('custo_fixo__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('custo_fixo__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('pagamento_custo_servico__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('pagamento_custo_extra__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('pagamento_parcela_divida__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('investimento__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('financiamento_movimentacao__isnull', True)), models.Q(('financiamento_movimentacao__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('pagamento_custo_servico__isnull', True), ('pagamento_custo_extra__isnull', True), ('pagamento_parcela_divida__isnull', True), ('investimento__isnull', True)), _connector='OR'), name='ck_lanc_fin_origem_unica'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('custo_fixo__isnull', False)), fields=('custo_fixo',), name='uq_lanc_fin_custo_fixo'),
        ),
    ]
