# Generated by Django 6.0.5 on 2026-05-21 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0025_backfill_lancamentos_custos_fixos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamentomovimentacao',
            name='contrato_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_financiamento', to='caixa.contratooperacional'),
        ),
        migrations.AddField(
            model_name='financiamentomovimentacao',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_financiamento', to='caixa.evento'),
        ),
        migrations.AddField(
            model_name='historicalinvestimento',
            name='contrato_operacional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.contratooperacional'),
        ),
        migrations.AddField(
            model_name='historicalinvestimento',
            name='evento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.evento'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='contrato_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investimentos', to='caixa.contratooperacional'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investimentos', to='caixa.evento'),
        ),
        migrations.AddIndex(
            model_name='financiamentomovimentacao',
            index=models.Index(fields=['contrato_operacional', 'data_prevista'], name='caixa_finan_contrat_626cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='financiamentomovimentacao',
            index=models.Index(fields=['evento', 'data_prevista'], name='caixa_finan_evento__fa6876_idx'),
        ),
        migrations.AddIndex(
            model_name='investimento',
            index=models.Index(fields=['contrato_operacional', 'data_prevista'], name='caixa_inves_contrat_1ea2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='investimento',
            index=models.Index(fields=['evento', 'data_prevista'], name='caixa_inves_evento__9d5a63_idx'),
        ),
    ]
