# Generated by Django 6.0.5 on 2026-05-21 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0026_financiamentomovimentacao_contrato_operacional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dividafinanceira',
            name='contrato_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividas_financeiras', to='caixa.contratooperacional'),
        ),
        migrations.AddField(
            model_name='dividafinanceira',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividas_financeiras', to='caixa.evento'),
        ),
        migrations.AddIndex(
            model_name='dividafinanceira',
            index=models.Index(fields=['contrato_operacional', 'data_contratacao'], name='caixa_divid_contrat_69b628_idx'),
        ),
        migrations.AddIndex(
            model_name='dividafinanceira',
            index=models.Index(fields=['evento', 'data_contratacao'], name='caixa_divid_evento__b8a47f_idx'),
        ),
    ]
