# Generated by Django 6.0.5 on 2026-05-21 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0028_baixafinanceira_historicalbaixafinanceira_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='obrigacaofinanceira',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('receita_operacional__isnull', False), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('evento_custo_servico__isnull', True), ('evento_custo_extra__isnull', True), ('parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True), ('origem', 'receita_operacional')), models.Q(('despesa_operacional__isnull', False), ('receita_operacional__isnull', True), ('custo_fixo__isnull', True), ('evento_custo_servico__isnull', True), ('evento_custo_extra__isnull', True), ('parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True), ('origem', 'despesa_operacional')), models.Q(('custo_fixo__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('evento_custo_servico__isnull', True), ('evento_custo_extra__isnull', True), ('parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True), ('origem', 'custo_fixo')), models.Q(('evento_custo_servico__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('evento_custo_extra__isnull', True), ('parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True), ('origem', 'custo_servico')), models.Q(('evento_custo_extra__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('evento_custo_servico__isnull', True), ('parcela_divida__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True), ('origem', 'custo_extra')), models.Q(('parcela_divida__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('evento_custo_servico__isnull', True), ('evento_custo_extra__isnull', True), ('investimento__isnull', True), ('financiamento_movimentacao__isnull', True), ('origem', 'parcela_divida')), models.Q(('investimento__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('evento_custo_servico__isnull', True), ('evento_custo_extra__isnull', True), ('parcela_divida__isnull', True), ('financiamento_movimentacao__isnull', True), ('origem', 'investimento')), models.Q(('financiamento_movimentacao__isnull', False), ('receita_operacional__isnull', True), ('despesa_operacional__isnull', True), ('custo_fixo__isnull', True), ('evento_custo_servico__isnull', True), ('evento_custo_extra__isnull', True), ('parcela_divida__isnull', True), ('investimento__isnull', True), ('origem', 'financiamento_movimentacao')), _connector='OR'), name='ck_obrig_fin_origem_consist'),
        ),
    ]
