# Generated by Django 6.0.5 on 2026-05-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0029_obrigacaofinanceira_ck_obrig_fin_origem_consist'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixafinanceira',
            name='fonte_escrita',
            field=models.CharField(choices=[('legacyAdapterSynced', 'Adapter legado sincronizado'), ('canonicalFirst', 'Canonical-first')], db_index=True, default='legacyAdapterSynced', help_text='Fonte de escrita que criou ou atualizou a baixa canonica.', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalbaixafinanceira',
            name='fonte_escrita',
            field=models.CharField(choices=[('legacyAdapterSynced', 'Adapter legado sincronizado'), ('canonicalFirst', 'Canonical-first')], db_index=True, default='legacyAdapterSynced', help_text='Fonte de escrita que criou ou atualizou a baixa canonica.', max_length=30),
        ),
    ]
