# Generated by Django 6.0.5 on 2026-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0030_baixafinanceira_fonte_escrita_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baixafinanceiraalocacao',
            options={'ordering': ['baixa', 'obrigacao', 'id'], 'verbose_name': 'Alocação de baixa financeira', 'verbose_name_plural': 'Alocações de baixas financeiras'},
        ),
        migrations.AlterModelOptions(
            name='configuracaofinanceira',
            options={'ordering': ['-data_inicio_vigencia', '-id'], 'verbose_name': 'Configuração financeira', 'verbose_name_plural': 'Configurações financeiras'},
        ),
        migrations.AlterModelOptions(
            name='contratooperacional',
            options={'ordering': ['-criado_em', '-id'], 'verbose_name': 'Contrato operacional', 'verbose_name_plural': 'Contratos operacionais'},
        ),
        migrations.AlterModelOptions(
            name='custofixo',
            options={'ordering': ['data_vencimento', 'descricao', 'id'], 'verbose_name': 'Custo fixo', 'verbose_name_plural': 'Custos fixos'},
        ),
        migrations.AlterModelOptions(
            name='despesaoperacional',
            options={'ordering': ['data_vencimento', 'id'], 'verbose_name': 'Despesa operacional', 'verbose_name_plural': 'Despesas operacionais'},
        ),
        migrations.AlterModelOptions(
            name='dividafinanceira',
            options={'ordering': ['-data_contratacao', '-id'], 'verbose_name': 'Dívida financeira', 'verbose_name_plural': 'Dívidas financeiras'},
        ),
        migrations.AlterModelOptions(
            name='eventocustoextra',
            options={'ordering': ['data_vencimento', 'id'], 'verbose_name': 'Custo extra do evento', 'verbose_name_plural': 'Custos extras do evento'},
        ),
        migrations.AlterModelOptions(
            name='eventocustoservico',
            options={'ordering': ['evento', 'servico__nome'], 'verbose_name': 'Custo de serviço do evento', 'verbose_name_plural': 'Custos de serviço dos eventos'},
        ),
        migrations.AlterModelOptions(
            name='financiamentomovimentacao',
            options={'ordering': ['-data_prevista', '-id'], 'verbose_name': 'Movimentação de financiamento', 'verbose_name_plural': 'Movimentações de financiamento'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontratooperacional',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Contrato operacional', 'verbose_name_plural': 'historical Contratos operacionais'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustofixo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Custo fixo', 'verbose_name_plural': 'historical Custos fixos'},
        ),
        migrations.AlterModelOptions(
            name='historicaldespesaoperacional',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Despesa operacional', 'verbose_name_plural': 'historical Despesas operacionais'},
        ),
        migrations.AlterModelOptions(
            name='historicaleventocustoextra',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Custo extra do evento', 'verbose_name_plural': 'historical Custos extras do evento'},
        ),
        migrations.AlterModelOptions(
            name='historicaleventocustoservico',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Custo de serviço do evento', 'verbose_name_plural': 'historical Custos de serviço dos eventos'},
        ),
        migrations.AlterModelOptions(
            name='historicallancamentofinanceiro',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Lançamento financeiro', 'verbose_name_plural': 'historical Lançamentos financeiros'},
        ),
        migrations.AlterModelOptions(
            name='historicalobrigacaofinanceira',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Obrigação financeira', 'verbose_name_plural': 'historical Obrigações financeiras'},
        ),
        migrations.AlterModelOptions(
            name='historicalpagamentoeventocustoextra',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pagamento de custo extra', 'verbose_name_plural': 'historical Pagamentos de custos extras'},
        ),
        migrations.AlterModelOptions(
            name='historicalpagamentoeventocustoservico',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pagamento de custo de serviço', 'verbose_name_plural': 'historical Pagamentos de custos de serviço'},
        ),
        migrations.AlterModelOptions(
            name='historicalreceitaoperacional',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Receita operacional', 'verbose_name_plural': 'historical Receitas operacionais'},
        ),
        migrations.AlterModelOptions(
            name='lancamentofinanceiro',
            options={'ordering': ['-data_lancamento', '-id'], 'verbose_name': 'Lançamento financeiro', 'verbose_name_plural': 'Lançamentos financeiros'},
        ),
        migrations.AlterModelOptions(
            name='obrigacaofinanceira',
            options={'ordering': ['data_vencimento', 'origem', 'descricao', 'id'], 'verbose_name': 'Obrigação financeira', 'verbose_name_plural': 'Obrigações financeiras'},
        ),
        migrations.AlterModelOptions(
            name='orcamentoitem',
            options={'ordering': ['id'], 'verbose_name': 'Item do orçamento', 'verbose_name_plural': 'Itens do orçamento'},
        ),
        migrations.AlterModelOptions(
            name='pagamentoeventocustoextra',
            options={'ordering': ['data_pagamento', 'id'], 'verbose_name': 'Pagamento de custo extra', 'verbose_name_plural': 'Pagamentos de custos extras'},
        ),
        migrations.AlterModelOptions(
            name='pagamentoeventocustoservico',
            options={'ordering': ['data_pagamento', 'id'], 'verbose_name': 'Pagamento de custo de serviço', 'verbose_name_plural': 'Pagamentos de custos de serviço'},
        ),
        migrations.AlterModelOptions(
            name='pagamentoparceladivida',
            options={'ordering': ['data_pagamento', 'id'], 'verbose_name': 'Pagamento de parcela', 'verbose_name_plural': 'Pagamentos de parcelas'},
        ),
        migrations.AlterModelOptions(
            name='parceladivida',
            options={'ordering': ['data_vencimento_atual', 'numero_parcela', 'id'], 'verbose_name': 'Parcela da dívida', 'verbose_name_plural': 'Parcelas das dívidas'},
        ),
        migrations.AlterModelOptions(
            name='receitaoperacional',
            options={'ordering': ['data_vencimento', 'id'], 'verbose_name': 'Receita operacional', 'verbose_name_plural': 'Receitas operacionais'},
        ),
        migrations.AlterField(
            model_name='baixafinanceira',
            name='chave_origem',
            field=models.CharField(blank=True, db_index=True, help_text='Chave estável da origem legada ou canônica da baixa.', max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='baixafinanceira',
            name='natureza',
            field=models.CharField(choices=[('receita_operacional', 'Receita operacional'), ('despesa_operacional', 'Despesa operacional'), ('custo_servico', 'Custo de serviço'), ('custo_extra', 'Custo extra'), ('parcela_divida', 'Parcela de dívida'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='eventocustoservico',
            name='alimentacao_quitada',
            field=models.BooleanField(default=False, verbose_name='Alimentação baixada'),
        ),
        migrations.AlterField(
            model_name='eventocustoservico',
            name='diarias_quitadas',
            field=models.BooleanField(default=False, verbose_name='Diárias baixadas'),
        ),
        migrations.AlterField(
            model_name='financiamentomovimentacao',
            name='categoria',
            field=models.CharField(choices=[('emprestimo', 'Empréstimo'), ('financiamento', 'Financiamento'), ('aporte_socio', 'Aporte de sócio'), ('retirada_socio', 'Retirada de sócio'), ('amortizacao', 'Amortização'), ('juros', 'Juros'), ('encargo_bancario', 'Encargo bancário'), ('outros', 'Outros')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalbaixafinanceira',
            name='chave_origem',
            field=models.CharField(blank=True, db_index=True, help_text='Chave estável da origem legada ou canônica da baixa.', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbaixafinanceira',
            name='natureza',
            field=models.CharField(choices=[('receita_operacional', 'Receita operacional'), ('despesa_operacional', 'Despesa operacional'), ('custo_servico', 'Custo de serviço'), ('custo_extra', 'Custo extra'), ('parcela_divida', 'Parcela de dívida'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='historicaleventocustoservico',
            name='alimentacao_quitada',
            field=models.BooleanField(default=False, verbose_name='Alimentação baixada'),
        ),
        migrations.AlterField(
            model_name='historicaleventocustoservico',
            name='diarias_quitadas',
            field=models.BooleanField(default=False, verbose_name='Diárias baixadas'),
        ),
        migrations.AlterField(
            model_name='historicallancamentofinanceiro',
            name='natureza',
            field=models.CharField(choices=[('receita_operacional', 'Receita operacional'), ('despesa_operacional', 'Despesa operacional'), ('custo_servico', 'Custo de serviço'), ('custo_extra', 'Custo extra'), ('parcela_divida', 'Parcela de dívida'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalobrigacaofinanceira',
            name='chave_origem',
            field=models.CharField(blank=True, db_index=True, help_text='Chave estável da origem legada ou canônica da obrigação.', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='historicalobrigacaofinanceira',
            name='natureza',
            field=models.CharField(choices=[('receita_operacional', 'Receita operacional'), ('despesa_operacional', 'Despesa operacional'), ('custo_servico', 'Custo de serviço'), ('custo_extra', 'Custo extra'), ('parcela_divida', 'Parcela de dívida'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalobrigacaofinanceira',
            name='origem',
            field=models.CharField(choices=[('receita_operacional', 'Receita operacional'), ('despesa_operacional', 'Despesa operacional'), ('custo_fixo', 'Custo fixo'), ('custo_servico', 'Custo de serviço'), ('custo_extra', 'Custo extra'), ('parcela_divida', 'Parcela FCF'), ('investimento', 'Investimento'), ('financiamento_movimentacao', 'Movimentação de financiamento')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='natureza',
            field=models.CharField(choices=[('receita_operacional', 'Receita operacional'), ('despesa_operacional', 'Despesa operacional'), ('custo_servico', 'Custo de serviço'), ('custo_extra', 'Custo extra'), ('parcela_divida', 'Parcela de dívida'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='obrigacaofinanceira',
            name='chave_origem',
            field=models.CharField(blank=True, db_index=True, help_text='Chave estável da origem legada ou canônica da obrigação.', max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='obrigacaofinanceira',
            name='natureza',
            field=models.CharField(choices=[('receita_operacional', 'Receita operacional'), ('despesa_operacional', 'Despesa operacional'), ('custo_servico', 'Custo de serviço'), ('custo_extra', 'Custo extra'), ('parcela_divida', 'Parcela de dívida'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='obrigacaofinanceira',
            name='origem',
            field=models.CharField(choices=[('receita_operacional', 'Receita operacional'), ('despesa_operacional', 'Despesa operacional'), ('custo_fixo', 'Custo fixo'), ('custo_servico', 'Custo de serviço'), ('custo_extra', 'Custo extra'), ('parcela_divida', 'Parcela FCF'), ('investimento', 'Investimento'), ('financiamento_movimentacao', 'Movimentação de financiamento')], db_index=True, max_length=40),
        ),
    ]
