# Generated by Django 6.0.5 on 2026-05-24 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0031_padroniza_verbose_names_financeiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamentomovimentacao',
            name='divida_financeira',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_entrada_fcf', to='caixa.dividafinanceira', verbose_name='Divida financeira de origem'),
        ),
    ]
