# Generated by Django 6.0.5 on 2026-05-24 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_credores_dividas(apps, schema_editor):
    Credor = apps.get_model('caixa', 'Credor')
    DividaFinanceira = apps.get_model('caixa', 'DividaFinanceira')

    nomes_credores = (
        DividaFinanceira.objects.exclude(credor='')
        .order_by('credor')
        .values_list('credor', flat=True)
        .distinct()
    )
    credores_por_nome = {}

    for nome in nomes_credores:
        nome_normalizado = nome.strip()
        if not nome_normalizado:
            continue

        credor, _criado = Credor.objects.get_or_create(nome=nome_normalizado)
        credores_por_nome[nome_normalizado] = credor

    for divida in DividaFinanceira.objects.exclude(credor='').only('id', 'credor').iterator():
        nome_normalizado = divida.credor.strip()
        credor = credores_por_nome.get(nome_normalizado)

        if credor is not None:
            DividaFinanceira.objects.filter(pk=divida.pk).update(
                credor=nome_normalizado,
                credor_cadastro_id=credor.pk,
            )


def desfazer_migracao_credores_dividas(apps, schema_editor):
    DividaFinanceira = apps.get_model('caixa', 'DividaFinanceira')
    DividaFinanceira.objects.update(credor_cadastro=None)


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0032_entrada_fcf_divida_financeira'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividafinanceira',
            name='credor',
            field=models.CharField(db_index=True, help_text='Alias textual preservado para filtros e integracoes legadas.', max_length=150, verbose_name='Credor legado'),
        ),
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=150, unique=True)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credores_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credores_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credor',
                'verbose_name_plural': 'Credores',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dividafinanceira',
            name='credor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dividas_financeiras', to='caixa.credor', verbose_name='Credor'),
        ),
        migrations.RunPython(
            migrar_credores_dividas,
            desfazer_migracao_credores_dividas,
        ),
        migrations.AddIndex(
            model_name='dividafinanceira',
            index=models.Index(fields=['credor_cadastro', 'status'], name='caixa_divid_credor__e3f2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='credor',
            index=models.Index(fields=['ativo', 'nome'], name='caixa_credo_ativo_389ee0_idx'),
        ),
    ]
