# Generated by Codex on 2026-05-31

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caixa", "0033_cadastro_credores_dividas"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrcamentoCustoExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("insumo", "Insumo"),
                            ("material", "Material"),
                            ("uniforme", "Uniforme"),
                            ("logistica", "Logística"),
                            ("comissao", "Comissão"),
                            ("outros", "Outros"),
                        ],
                        db_index=True,
                        default="insumo",
                        max_length=30,
                    ),
                ),
                ("descricao", models.CharField(max_length=150)),
                (
                    "valor_previsto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                ("data_vencimento", models.DateField(db_index=True)),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "evento_custo_extra",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orcamento_origem",
                        to="caixa.eventocustoextra",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custos_extras",
                        to="caixa.orcamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custo extra do orcamento",
                "verbose_name_plural": "Custos extras do orcamento",
                "ordering": ["data_vencimento", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="orcamentocustoextra",
            index=models.Index(
                fields=["orcamento", "data_vencimento"],
                name="caixa_orcam_orcamen_7badce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orcamentocustoextra",
            index=models.Index(
                fields=["categoria", "data_vencimento"],
                name="caixa_orcam_categor_f2e9aa_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="orcamentocustoextra",
            constraint=models.CheckConstraint(
                condition=models.Q(valor_previsto__gte=0),
                name="ck_orcamento_custo_extra_valor_nn",
            ),
        ),
    ]
