# Generated by Django 6.0.6 on 2026-07-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caixa", "0039_orcamento_approve_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="numero",
            field=models.CharField(max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalevento",
            name="numero",
            field=models.CharField(db_index=True, max_length=34),
        ),
    ]
