# Generated by Django 6.0.6 on 2026-07-29 17:29

import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0042_demo_seed_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServidor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=150)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('RG', 'RG'), ('OUTRO', 'Outro')], default='CPF', max_length=10)),
                ('documento', models.CharField(db_index=True, max_length=32)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('tipo_vinculo', models.CharField(choices=[('DIARISTA', 'Diarista'), ('MENSALISTA', 'Mensalista')], db_index=True, default='DIARISTA', max_length=12)),
                ('exibir_como_socio', models.BooleanField(default=False, verbose_name='Exibir como Sócio')),
                ('salario_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_inicio_contrato', models.DateField(blank=True, db_index=True, null=True)),
                ('data_fim_contrato', models.DateField(blank=True, db_index=True, null=True)),
                ('dia_pagamento_salario', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_autorizacao_custo_salarial', models.DateField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Servidor',
                'verbose_name_plural': 'historical Servidores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=150)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('RG', 'RG'), ('OUTRO', 'Outro')], default='CPF', max_length=10)),
                ('documento', models.CharField(max_length=32, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('tipo_vinculo', models.CharField(choices=[('DIARISTA', 'Diarista'), ('MENSALISTA', 'Mensalista')], db_index=True, default='DIARISTA', max_length=12)),
                ('exibir_como_socio', models.BooleanField(default=False, verbose_name='Exibir como Sócio')),
                ('salario_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_inicio_contrato', models.DateField(blank=True, db_index=True, null=True)),
                ('data_fim_contrato', models.DateField(blank=True, db_index=True, null=True)),
                ('dia_pagamento_salario', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_autorizacao_custo_salarial', models.DateField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['nome', 'id'],
                'permissions': [('view_salario_servidor', 'Pode visualizar salário de servidor'), ('change_salario_servidor', 'Pode alterar salário de servidor'), ('view_dados_sensiveis_servidor', 'Pode visualizar dados sensíveis de servidor')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalServidorServico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.servico')),
                ('servidor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.servidor')),
            ],
            options={
                'verbose_name': 'historical Serviço do servidor',
                'verbose_name_plural': 'historical Serviços dos servidores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHistoricoSalarialServidor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('servidor_nome_snapshot', models.CharField(max_length=150)),
                ('servidor_id_snapshot', models.PositiveBigIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.servidor')),
            ],
            options={
                'verbose_name': 'historical Histórico salarial do servidor',
                'verbose_name_plural': 'historical Históricos salariais dos servidores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServidorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_servidor_servico_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_servidor_servico_criados', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_servidores', to='caixa.servico')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_servicos', to='caixa.servidor')),
            ],
            options={
                'verbose_name': 'Serviço do servidor',
                'verbose_name_plural': 'Serviços dos servidores',
                'ordering': ['servidor__nome', 'servico__nome', 'id'],
            },
        ),
        migrations.AddField(
            model_name='servidor',
            name='servicos',
            field=models.ManyToManyField(related_name='servidores', through='caixa.ServidorServico', to='caixa.servico'),
        ),
        migrations.CreateModel(
            name='HistoricoSalarialServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_nome_snapshot', models.CharField(max_length=150)),
                ('servidor_id_snapshot', models.PositiveBigIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_salariais_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_salariais_criados', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_salariais', to='caixa.servidor')),
            ],
            options={
                'verbose_name': 'Histórico salarial do servidor',
                'verbose_name_plural': 'Históricos salariais dos servidores',
                'ordering': ['-data_inicio', '-id'],
                'indexes': [models.Index(fields=['servidor', 'data_inicio', 'data_fim'], name='caixa_histo_servido_af3934_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='ck_hist_salario_valor_pos'), models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='ck_hist_salario_periodo'), models.UniqueConstraint(condition=models.Q(('servidor__isnull', False)), fields=('servidor', 'data_inicio'), name='uq_hist_salario_inicio')],
            },
        ),
        migrations.AddIndex(
            model_name='servidorservico',
            index=models.Index(fields=['servidor', 'ativo'], name='caixa_servi_servido_7546c1_idx'),
        ),
        migrations.AddIndex(
            model_name='servidorservico',
            index=models.Index(fields=['servico', 'ativo'], name='caixa_servi_servico_71c4e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='servidorservico',
            constraint=models.UniqueConstraint(fields=('servidor', 'servico'), name='uq_servidor_servico'),
        ),
        migrations.AddIndex(
            model_name='servidor',
            index=models.Index(fields=['ativo', 'tipo_vinculo', 'nome'], name='caixa_servi_ativo_61398c_idx'),
        ),
        migrations.AddIndex(
            model_name='servidor',
            index=models.Index(fields=['tipo_documento', 'documento'], name='caixa_servi_tipo_do_04b725_idx'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('documento'), name='uq_servidor_documento_ci'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_vinculo__in', ['DIARISTA', 'MENSALISTA'])), name='ck_servidor_vinculo_valid'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('salario_mensal__gt', 0), ('tipo_vinculo', 'MENSALISTA')), models.Q(('data_autorizacao_custo_salarial__isnull', True), ('data_fim_contrato__isnull', True), ('data_inicio_contrato__isnull', True), ('dia_pagamento_salario__isnull', True), ('salario_mensal__isnull', True), ('tipo_vinculo', 'DIARISTA')), _connector='OR'), name='ck_servidor_salario_vinculo'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim_contrato__isnull', True), ('data_inicio_contrato__isnull', True), ('data_fim_contrato__gte', models.F('data_inicio_contrato')), _connector='OR'), name='ck_servidor_periodo_contrato'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.CheckConstraint(condition=models.Q(('dia_pagamento_salario__isnull', True), models.Q(('dia_pagamento_salario__gte', 1), ('dia_pagamento_salario__lte', 31)), _connector='OR'), name='ck_servidor_dia_pagamento'),
        ),
    ]
