# Generated by Django 6.0.6 on 2026-07-29 17:31

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0043_servidores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoIdempotenteRecorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(max_length=80)),
                ('chave', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('concluida', 'Concluída')], default='concluida', max_length=20)),
                ('http_status', models.PositiveSmallIntegerField()),
                ('resposta_segura', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Requisição idempotente de recorrência',
                'verbose_name_plural': 'Requisições idempotentes de recorrência',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='custofixo',
            name='competencia',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='custofixo',
            name='historico_salarial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custos_materializados', to='caixa.historicosalarialservidor'),
        ),
        migrations.AddField(
            model_name='custofixo',
            name='origem_recorrencia',
            field=models.CharField(choices=[('legado', 'Legado ou avulso'), ('plano', 'Plano recorrente'), ('salario', 'Salário mensal')], db_index=True, default='legado', max_length=20),
        ),
        migrations.AddField(
            model_name='custofixo',
            name='servidor_nome_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='custofixo',
            name='servidor_salario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_salariais', to='caixa.servidor'),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='competencia',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='historico_salarial',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.historicosalarialservidor'),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='origem_recorrencia',
            field=models.CharField(choices=[('legado', 'Legado ou avulso'), ('plano', 'Plano recorrente'), ('salario', 'Salário mensal')], db_index=True, default='legado', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='servidor_nome_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='servidor_salario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.servidor'),
        ),
        migrations.CreateModel(
            name='AuditoriaCustoRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_tecnico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_evento', models.CharField(choices=[('materializacao', 'Materialização'), ('recuperacao', 'Recuperação'), ('ativacao', 'Ativação'), ('expurgo', 'Expurgo')], max_length=24)),
                ('origem', models.CharField(choices=[('api', 'API'), ('command', 'Command'), ('admin', 'Admin'), ('ativacao', 'Ativação'), ('sistema', 'Sistema')], max_length=16)),
                ('competencia', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('bloqueado', 'Bloqueado'), ('conflito', 'Conflito'), ('falha', 'Falha')], max_length=16)),
                ('codigo_motivo', models.CharField(choices=[('MATERIALIZED', 'Materializado'), ('RECOVERED', 'Competência recuperada'), ('ALREADY_MATERIALIZED', 'Já materializado'), ('DOMAIN_BLOCKED', 'Bloqueio de domínio'), ('CONCURRENCY_RETRY_EXHAUSTED', 'Concorrência esgotada'), ('UNEXPECTED_MATERIALIZATION_FAILURE', 'Falha inesperada'), ('SERVER_ACTIVATED', 'Servidor ativado'), ('SERVER_ALREADY_ACTIVE', 'Servidor já ativado'), ('ACTIVATION_BLOCKED', 'Ativação bloqueada'), ('ACTIVATION_FAILED', 'Falha na ativação'), ('RETENTION_PURGE', 'Expurgo de retenção')], max_length=48)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('chave_agregacao', models.CharField(db_index=True, max_length=64)),
                ('first_occurred_at', models.DateTimeField()),
                ('last_occurred_at', models.DateTimeField(db_index=True)),
                ('occurrences_count', models.PositiveIntegerField(default=1)),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de custo recorrente',
                'verbose_name_plural': 'Auditoria de custos recorrentes',
                'ordering': ['-last_occurred_at', '-id'],
                'permissions': [('view_auditoria_custos_recorrentes', 'Pode consultar auditoria de custos recorrentes')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EstadoAgregacaoAuditoriaRecorrente',
            fields=[
                ('chave_agregacao', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultimo_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='caixa.auditoriacustorecorrente')),
            ],
            options={
                'verbose_name': 'Estado de agregação de auditoria recorrente',
                'verbose_name_plural': 'Estados de agregação de auditoria recorrente',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PlanoCustoRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel'), ('energia', 'Energia'), ('agua', 'Água'), ('internet', 'Internet'), ('telefone', 'Telefone'), ('salario', 'Salário'), ('contador', 'Contador'), ('sistema', 'Sistema'), ('imposto', 'Imposto'), ('outro', 'Outro')], db_index=True, default='outro', max_length=30)),
                ('origem', models.CharField(choices=[('comum', 'Custo recorrente'), ('salario', 'Salário mensal')], db_index=True, default='comum', max_length=20)),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal')], default='mensal', max_length=12)),
                ('valor_previsto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=1)),
                ('data_autorizacao_materializacao', models.DateField(db_index=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_custos_recorrentes_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_custos_recorrentes_criados', to=settings.AUTH_USER_MODEL)),
                ('custo_legado_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planos_renovacao', to='caixa.custofixo')),
                ('plano_renovado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renovacoes', to='caixa.planocustorecorrente')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planos_custos_recorrentes', to='caixa.servidor')),
            ],
            options={
                'verbose_name': 'Plano de custo recorrente',
                'verbose_name_plural': 'Planos de custos recorrentes',
                'ordering': ['data_inicio', 'descricao', 'id'],
                'permissions': [('materialize_planocustorecorrente', 'Pode materializar plano de custo recorrente')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlanoCustoRecorrente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel'), ('energia', 'Energia'), ('agua', 'Água'), ('internet', 'Internet'), ('telefone', 'Telefone'), ('salario', 'Salário'), ('contador', 'Contador'), ('sistema', 'Sistema'), ('imposto', 'Imposto'), ('outro', 'Outro')], db_index=True, default='outro', max_length=30)),
                ('origem', models.CharField(choices=[('comum', 'Custo recorrente'), ('salario', 'Salário mensal')], db_index=True, default='comum', max_length=20)),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal')], default='mensal', max_length=12)),
                ('valor_previsto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=1)),
                ('data_autorizacao_materializacao', models.DateField(db_index=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('custo_legado_referencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.custofixo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.servidor')),
                ('plano_renovado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.planocustorecorrente')),
            ],
            options={
                'verbose_name': 'historical Plano de custo recorrente',
                'verbose_name_plural': 'historical Planos de custos recorrentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='auditoriacustorecorrente',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='caixa.planocustorecorrente'),
        ),
        migrations.AddField(
            model_name='custofixo',
            name='plano_recorrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='caixa.planocustorecorrente'),
        ),
        migrations.AddField(
            model_name='historicalcustofixo',
            name='plano_recorrente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.planocustorecorrente'),
        ),
        migrations.AddIndex(
            model_name='custofixo',
            index=models.Index(fields=['origem_recorrencia', 'data_vencimento'], name='caixa_custo_origem__27a67d_idx'),
        ),
        migrations.AddIndex(
            model_name='custofixo',
            index=models.Index(fields=['plano_recorrente', 'competencia'], name='caixa_custo_plano_r_6d0182_idx'),
        ),
        migrations.AddConstraint(
            model_name='custofixo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competencia__isnull', True), ('plano_recorrente__isnull', True)), models.Q(('competencia__isnull', False), ('plano_recorrente__isnull', False)), _connector='OR'), name='ck_custo_fixo_plano_comp'),
        ),
        migrations.AddConstraint(
            model_name='custofixo',
            constraint=models.UniqueConstraint(condition=models.Q(('plano_recorrente__isnull', False)), fields=('plano_recorrente', 'competencia'), name='uq_custo_fixo_plano_comp'),
        ),
        migrations.AddField(
            model_name='requisicaoidempotenterecorrencia',
            name='ator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='planocustorecorrente',
            index=models.Index(fields=['ativo', 'data_inicio', 'data_fim'], name='caixa_plano_ativo_de7902_idx'),
        ),
        migrations.AddIndex(
            model_name='planocustorecorrente',
            index=models.Index(fields=['origem', 'ativo'], name='caixa_plano_origem_3bd454_idx'),
        ),
        migrations.AddIndex(
            model_name='planocustorecorrente',
            index=models.Index(fields=['servidor', 'ativo'], name='caixa_plano_servido_51b01f_idx'),
        ),
        migrations.AddConstraint(
            model_name='planocustorecorrente',
            constraint=models.CheckConstraint(condition=models.Q(('dia_vencimento__gte', 1), ('dia_vencimento__lte', 31)), name='ck_plano_custo_dia_venc'),
        ),
        migrations.AddConstraint(
            model_name='planocustorecorrente',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='ck_plano_custo_periodo'),
        ),
        migrations.AddConstraint(
            model_name='planocustorecorrente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origem', 'comum'), ('servidor__isnull', True), ('valor_previsto__gt', 0)), models.Q(('categoria', 'salario'), ('origem', 'salario'), ('servidor__isnull', False), ('valor_previsto__isnull', True)), _connector='OR'), name='ck_plano_custo_origem'),
        ),
        migrations.AddConstraint(
            model_name='planocustorecorrente',
            constraint=models.UniqueConstraint(condition=models.Q(('origem', 'salario'), ('servidor__isnull', False)), fields=('servidor',), name='uq_plano_salario_servidor'),
        ),
        migrations.AddConstraint(
            model_name='planocustorecorrente',
            constraint=models.UniqueConstraint(condition=models.Q(('custo_legado_referencia__isnull', False)), fields=('custo_legado_referencia',), name='uq_plano_renovacao_legado'),
        ),
        migrations.AddConstraint(
            model_name='planocustorecorrente',
            constraint=models.UniqueConstraint(condition=models.Q(('plano_renovado__isnull', False)), fields=('plano_renovado',), name='uq_plano_renovacao_plano'),
        ),
        migrations.AddIndex(
            model_name='auditoriacustorecorrente',
            index=models.Index(fields=['plano', 'competencia'], name='caixa_audit_plano_i_ea8d89_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriacustorecorrente',
            index=models.Index(fields=['tipo_evento', 'origem', 'status'], name='caixa_audit_tipo_ev_1104e1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriacustorecorrente',
            index=models.Index(fields=['chave_agregacao', 'last_occurred_at'], name='caixa_audit_chave_a_08ee9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditoriacustorecorrente',
            constraint=models.CheckConstraint(condition=models.Q(('occurrences_count__gte', 1)), name='ck_audit_rec_ocorrencias_pos'),
        ),
        migrations.AddIndex(
            model_name='requisicaoidempotenterecorrencia',
            index=models.Index(fields=['criado_em'], name='caixa_requi_criado__1778e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisicaoidempotenterecorrencia',
            constraint=models.UniqueConstraint(fields=('escopo', 'chave'), name='uq_idempotencia_rec_escopo_chave'),
        ),
    ]
