# Generated by Django 6.0.6 on 2026-07-29 17:32

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0044_recorrencias_salariais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalParticipacaoServidorEvento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_vinculo', models.CharField(choices=[('DIARISTA', 'Diarista'), ('MENSALISTA', 'Mensalista')], db_index=True, max_length=12)),
                ('quantidade_dias', models.PositiveIntegerField(default=1)),
                ('quantidade_horas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_editado_manualmente', models.BooleanField(db_index=True, default=False)),
                ('motivo_edicao', models.TextField(blank=True)),
                ('valor_anterior_edicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_novo_edicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('editado_em', models.DateTimeField(blank=True, null=True)),
                ('servidor_nome_snapshot', models.CharField(max_length=150)),
                ('servidor_id_snapshot', models.PositiveBigIntegerField()),
                ('servidor_identificador_snapshot', models.CharField(blank=True, max_length=8)),
                ('servico_nome_snapshot', models.CharField(max_length=100)),
                ('servico_codigo_snapshot', models.CharField(max_length=50)),
                ('salario_mensal_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidade_cobranca_snapshot', models.CharField(max_length=10)),
                ('horas_base_diaria_snapshot', models.PositiveIntegerField(default=8)),
                ('regra_calculo_snapshot', models.CharField(default='HORAS_EQUIVALENTES', max_length=40)),
                ('valor_total_servico_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantidade_servidores_rateio_snapshot', models.PositiveIntegerField(default=1)),
                ('servidor_excluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.evento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.servico')),
                ('servidor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.servidor')),
                ('servidor_excluido_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Participação de servidor no evento',
                'verbose_name_plural': 'historical Participações de servidores nos eventos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ParticipacaoServidorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vinculo', models.CharField(choices=[('DIARISTA', 'Diarista'), ('MENSALISTA', 'Mensalista')], db_index=True, max_length=12)),
                ('quantidade_dias', models.PositiveIntegerField(default=1)),
                ('quantidade_horas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_editado_manualmente', models.BooleanField(db_index=True, default=False)),
                ('motivo_edicao', models.TextField(blank=True)),
                ('valor_anterior_edicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_novo_edicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('editado_em', models.DateTimeField(blank=True, null=True)),
                ('servidor_nome_snapshot', models.CharField(max_length=150)),
                ('servidor_id_snapshot', models.PositiveBigIntegerField()),
                ('servidor_identificador_snapshot', models.CharField(blank=True, max_length=8)),
                ('servico_nome_snapshot', models.CharField(max_length=100)),
                ('servico_codigo_snapshot', models.CharField(max_length=50)),
                ('salario_mensal_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidade_cobranca_snapshot', models.CharField(max_length=10)),
                ('horas_base_diaria_snapshot', models.PositiveIntegerField(default=8)),
                ('regra_calculo_snapshot', models.CharField(default='HORAS_EQUIVALENTES', max_length=40)),
                ('valor_total_servico_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantidade_servidores_rateio_snapshot', models.PositiveIntegerField(default=1)),
                ('servidor_excluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_servidores_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_servidores_criadas', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_participacao_editados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_servidores', to='caixa.evento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_servidores', to='caixa.servico')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_eventos', to='caixa.servidor')),
                ('servidor_excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_de_servidores_excluidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participação de servidor no evento',
                'verbose_name_plural': 'Participações de servidores nos eventos',
                'ordering': ['evento', 'servico__nome', 'servidor_nome_snapshot', 'id'],
                'permissions': [('view_custos_servidor', 'Pode visualizar custos por servidor'), ('manage_participacao_servidor', 'Pode gerenciar participação de servidor'), ('change_valor_distribuido_servidor', 'Pode editar valor distribuído'), ('recalculate_custos_servidor', 'Pode recalcular custos por servidor'), ('view_apropriacao_servidor', 'Pode visualizar apropriação gerencial')],
            },
        ),
        migrations.CreateModel(
            name='ServidorEventoDiaTrabalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('quantidade_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_trabalhados', to='caixa.participacaoservidorevento')),
            ],
            options={
                'verbose_name': 'Dia trabalhado por servidor no evento',
                'verbose_name_plural': 'Dias trabalhados por servidores nos eventos',
                'ordering': ['participacao_id', 'data', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='participacaoservidorevento',
            index=models.Index(fields=['evento', 'servico', 'tipo_vinculo'], name='caixa_parti_evento__4d5169_idx'),
        ),
        migrations.AddIndex(
            model_name='participacaoservidorevento',
            index=models.Index(fields=['servidor', 'evento'], name='caixa_parti_servido_b9f80b_idx'),
        ),
        migrations.AddIndex(
            model_name='participacaoservidorevento',
            index=models.Index(fields=['servidor_excluido_em', 'evento'], name='caixa_parti_servido_80de8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='participacaoservidorevento',
            constraint=models.UniqueConstraint(condition=models.Q(('servidor__isnull', False)), fields=('servidor', 'evento', 'servico'), name='uq_part_servidor_evento_serv'),
        ),
        migrations.AddConstraint(
            model_name='participacaoservidorevento',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_dias__gt', 0), ('quantidade_horas__gt', 0), _connector='OR'), name='ck_part_trabalho_pos'),
        ),
        migrations.AddConstraint(
            model_name='participacaoservidorevento',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_horas__gte', 0)), name='ck_part_horas_nn'),
        ),
        migrations.AddConstraint(
            model_name='participacaoservidorevento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_calculado__gte', 0), ('valor_final__gte', 0), ('valor_total_servico_snapshot__gte', 0)), name='ck_part_valores_nn'),
        ),
        migrations.AddConstraint(
            model_name='participacaoservidorevento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_editado_manualmente', False), models.Q(('motivo_edicao', ''), _negated=True), _connector='OR'), name='ck_part_manual_motivo'),
        ),
        migrations.AddConstraint(
            model_name='participacaoservidorevento',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_vinculo__in', ['DIARISTA', 'MENSALISTA'])), name='ck_part_vinculo_valid'),
        ),
        migrations.AddConstraint(
            model_name='servidoreventodiatrabalhado',
            constraint=models.UniqueConstraint(fields=('participacao', 'data'), name='uq_part_servidor_dia_trab'),
        ),
        migrations.AddConstraint(
            model_name='servidoreventodiatrabalhado',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_horas__isnull', True), ('quantidade_horas__gt', 0), _connector='OR'), name='ck_part_dia_horas_pos'),
        ),
    ]
