# Generated by Django 6.0.6 on 2026-08-10 00:35

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0046_recalcular_totais_orcamentos_editaveis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHistoricoJornadaMensalServidor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('servidor_nome_snapshot', models.CharField(max_length=150)),
                ('servidor_id_snapshot', models.PositiveBigIntegerField()),
                ('horas_mensais', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('744.00'))])),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Histórico de jornada mensal do servidor',
                'verbose_name_plural': 'historical Históricos de jornada mensal dos servidores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricoJornadaMensalServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_nome_snapshot', models.CharField(max_length=150)),
                ('servidor_id_snapshot', models.PositiveBigIntegerField()),
                ('horas_mensais', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('744.00'))])),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Histórico de jornada mensal do servidor',
                'verbose_name_plural': 'Históricos de jornada mensal dos servidores',
                'ordering': ['-data_inicio', '-id'],
            },
        ),
        migrations.AddField(
            model_name='historicalservidor',
            name='carga_horaria_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('744.00'))]),
        ),
        migrations.AddField(
            model_name='servidor',
            name='carga_horaria_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('744.00'))]),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('carga_horaria_mensal__isnull', True), ('tipo_vinculo', 'MENSALISTA')), models.Q(('carga_horaria_mensal__gt', 0), ('carga_horaria_mensal__lte', Decimal('744.00')), ('tipo_vinculo', 'MENSALISTA')), models.Q(('carga_horaria_mensal__isnull', True), ('tipo_vinculo', 'DIARISTA')), _connector='OR'), name='ck_servidor_jornada_mensal'),
        ),
        migrations.AddField(
            model_name='historicalhistoricojornadamensalservidor',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhistoricojornadamensalservidor',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhistoricojornadamensalservidor',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhistoricojornadamensalservidor',
            name='servidor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.servidor'),
        ),
        migrations.AddField(
            model_name='historicojornadamensalservidor',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_jornada_mensal_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicojornadamensalservidor',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_jornada_mensal_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicojornadamensalservidor',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_jornada_mensal', to='caixa.servidor'),
        ),
        migrations.AddIndex(
            model_name='historicojornadamensalservidor',
            index=models.Index(fields=['servidor', 'data_inicio', 'data_fim'], name='caixa_histo_servido_0b6de6_idx'),
        ),
        migrations.AddIndex(
            model_name='historicojornadamensalservidor',
            index=models.Index(fields=['servidor_id_snapshot', 'data_inicio', 'data_fim'], name='caixa_histo_servido_4ae0e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicojornadamensalservidor',
            constraint=models.CheckConstraint(condition=models.Q(('horas_mensais__gt', 0), ('horas_mensais__lte', Decimal('744.00'))), name='ck_hist_jornada_horas'),
        ),
        migrations.AddConstraint(
            model_name='historicojornadamensalservidor',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='ck_hist_jornada_periodo'),
        ),
        migrations.AddConstraint(
            model_name='historicojornadamensalservidor',
            constraint=models.UniqueConstraint(fields=('servidor_id_snapshot', 'data_inicio'), name='uq_hist_jornada_snapshot_inicio'),
        ),
    ]
